### ISSUE TITLE
Suggestion to improve

### ISSUE THREAD

**Issue by rgaiacs** [widdowquinn/Teaching-Data-Visualisation#1]
On

> What do the shape and record elements look like?
> 
> You can inspect the shape and record elements to see what data they hold either by looking at it directly, or using the **dict** method of the element, e.g.:

can we replace split it to mention the memory address? Maybe something like

> You can inspect the shape and record elements to see what data they hold by looking at it directly, e.g. `shapes[0]` or `records[0]`. `shapes[0]` is of an non-standard type so Python returned only the memory address but we can use `.__dict__` to get the content.

**Comment by widdowquinn** [comment]
Agreed - that's much better and clearer, thank you.

Added in commit 0d5ad1f
